# This is a basic workflow to help you get started with Actions

name: Sync stories

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: Checkout storycoder.dev repo
        uses: actions/checkout@v3
        with:
          repository: roseTech/storycoder.dev 
          path: './storycoder.dev'
      - name: Get new commits
        run: |
          cd "storycoder.dev"
          echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
          cd ..
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
      - name: Run examples
        run: npm run examples
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
      - name: Run update
        run: npm run update
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        env:
              WP_URL: ${{ vars.WP_URL }}
              WP_API_USERNAME: ${{ secrets.WP_API_USERNAME }}
              WP_API_PASSWORD: ${{ secrets.WP_API_PASSWORD}}
              STORIES_ROOT: ${{ vars.STORIES_ROOT }}
